version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
    networks:
      - wall-network

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    environment:
      - API_URL=${API_URL:-http://localhost:3000}
      - API_HOST=${API_HOST:-localhost}
      - API_PORT=${API_PORT:-3000}
    networks:
      - wall-network
    depends_on:
      - api

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    networks:
      - wall-network

networks:
  wall-network:
    driver: bridge

volumes:
  redis-data: